#!/usr/bin/env python3
"""Validate RustTorch's PyTorch compatibility ledger and generated page."""

from __future__ import annotations

import argparse
from pathlib import Path, PurePosixPath
import re
import sys
import tomllib
from typing import Any


TOP_LEVEL_FIELDS = {
    "format_version",
    "package",
    "crate",
    "tch",
    "pytorch_reference",
    "pytorch_commit",
    "api",
}
EXPECTED_METADATA = {
    "format_version": 2,
    "package": "rusttorch",
    "crate": "rusttorch",
    "tch": "0.26.0",
    "pytorch_reference": "v2.13.0",
    "pytorch_commit": "cf30153",
}
ROW_FIELDS = {
    "id",
    "python_symbols",
    "rust_symbols",
    "status",
    "implementation",
    "scope",
    "source",
    "evidence",
    "notes",
}
STATUSES = {"supported", "partial", "python_only", "planned", "not_supported"}
IMPLEMENTATIONS = {"libtorch", "rusttorch", "mixed", "none"}
NO_REQUIRED_RUST_SURFACE = {"python_only", "planned", "not_supported"}
ID_PATTERN = re.compile(r"^[a-z0-9]+(?:[._-][a-z0-9]+)*$")
TEST_NAME_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
GENERATED_HEADER = (
    "<!-- Generated by scripts/check-compatibility.py. Do not edit directly. -->\n"
    "# API coverage\n"
)


def load_ledger(path: Path) -> dict[str, Any]:
    """Load a TOML compatibility ledger from *path*."""

    with path.open("rb") as ledger_file:
        return tomllib.load(ledger_file)


def _unknown_and_missing(
    value: dict[str, Any], expected: set[str], context: str
) -> list[str]:
    errors = [f"{context}: unknown field '{field}'" for field in sorted(value.keys() - expected)]
    errors.extend(
        f"{context}: missing required field '{field}'"
        for field in sorted(expected - value.keys())
    )
    return errors


def _string_list(value: Any, context: str, *, allow_empty: bool) -> tuple[list[str], list[str]]:
    if not isinstance(value, list):
        return [], [f"{context} must be an array of strings"]
    errors: list[str] = []
    if not allow_empty and not value:
        errors.append(f"{context} must not be empty")
    if any(not isinstance(item, str) or not item.strip() for item in value):
        errors.append(f"{context} must contain only nonempty strings")
    strings = [item for item in value if isinstance(item, str)]
    if len(strings) != len(set(strings)):
        errors.append(f"{context} must not contain duplicates")
    return strings, errors


def _safe_relative_path(value: Any) -> bool:
    if not isinstance(value, str) or not value or "\\" in value or ":" in value:
        return False
    path = PurePosixPath(value)
    return (
        not path.is_absolute()
        and all(part not in {"", ".", ".."} for part in path.parts)
        and value == path.as_posix()
    )


def _declaration_exists(path: Path, test_name: str) -> bool:
    if path.suffix not in {".rs", ".py"}:
        return True
    contents = path.read_text(encoding="utf-8")
    if path.suffix == ".rs":
        declaration = re.compile(
            rf"^\s*(?:(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?)fn\s+{re.escape(test_name)}\s*(?:<[^>]*>\s*)?\(",
            re.MULTILINE,
        )
    else:
        declaration = re.compile(
            rf"^\s*(?:async\s+)?def\s+{re.escape(test_name)}\s*\(", re.MULTILINE
        )
    return declaration.search(contents) is not None


def _validate_evidence(root: Path, row_id: str, entries: list[str]) -> list[str]:
    errors: list[str] = []
    for entry in entries:
        if entry.count("::") != 1:
            errors.append(
                f"{row_id}.evidence: '{entry}' must use repo-relative-file::exact_test_name"
            )
            continue
        relative_path, test_name = entry.split("::")
        if not _safe_relative_path(relative_path) or not TEST_NAME_PATTERN.fullmatch(test_name):
            errors.append(f"{row_id}.evidence: malformed entry '{entry}'")
            continue
        evidence_path = root / relative_path
        if not evidence_path.is_file():
            errors.append(f"{row_id}.evidence: file '{relative_path}' does not exist")
            continue
        if not _declaration_exists(evidence_path, test_name):
            errors.append(
                f"{row_id}.evidence: declaration '{test_name}' does not exist in '{relative_path}'"
            )
    return errors


def _validate_manifest(root: Path, ledger: dict[str, Any]) -> list[str]:
    manifest_path = root / "Cargo.toml"
    if not manifest_path.is_file():
        return ["Cargo.toml: package, crate, and tch metadata cannot be validated"]
    try:
        with manifest_path.open("rb") as manifest_file:
            manifest = tomllib.load(manifest_file)
    except (OSError, tomllib.TOMLDecodeError) as error:
        return [f"Cargo.toml: cannot read metadata: {error}"]

    errors: list[str] = []
    package_name = manifest.get("package", {}).get("name")
    if package_name != ledger.get("package"):
        errors.append(
            f"package: ledger value {ledger.get('package')!r} does not match Cargo package {package_name!r}"
        )
    crate_name = manifest.get("lib", {}).get("name")
    if crate_name != ledger.get("crate"):
        errors.append(
            f"crate: ledger value {ledger.get('crate')!r} does not match Cargo library {crate_name!r}"
        )
    dependency = manifest.get("dependencies", {}).get("tch")
    dependency_version = dependency.get("version") if isinstance(dependency, dict) else dependency
    if dependency_version != ledger.get("tch"):
        errors.append(
            f"tch: ledger value {ledger.get('tch')!r} does not match Cargo dependency {dependency_version!r}"
        )
    return errors


def validate_ledger(root: Path, ledger: dict[str, Any]) -> list[str]:
    """Return every schema, metadata, and evidence error in *ledger*."""

    if not isinstance(ledger, dict):
        return ["ledger must be a TOML table"]

    errors = _unknown_and_missing(ledger, TOP_LEVEL_FIELDS, "ledger")
    for field, expected in EXPECTED_METADATA.items():
        if field in ledger and ledger[field] != expected:
            errors.append(f"{field}: expected {expected!r}, found {ledger[field]!r}")

    rows = ledger.get("api")
    if not isinstance(rows, list):
        errors.append("api must be an array of tables")
        rows = []

    ids: list[str] = []
    for index, row in enumerate(rows):
        if not isinstance(row, dict):
            errors.append(f"api[{index}] must be a table")
            continue
        raw_id = row.get("id")
        row_id = raw_id if isinstance(raw_id, str) and raw_id else f"api[{index}]"
        errors.extend(_unknown_and_missing(row, ROW_FIELDS, row_id))
        if not isinstance(raw_id, str) or ID_PATTERN.fullmatch(raw_id) is None:
            errors.append(f"{row_id}.id must be a stable lowercase dotted identifier")
        else:
            ids.append(raw_id)

        status = row.get("status")
        implementation = row.get("implementation")
        if status not in STATUSES:
            errors.append(f"{row_id}.status must be one of {sorted(STATUSES)}")
        if implementation not in IMPLEMENTATIONS:
            errors.append(
                f"{row_id}.implementation must be one of {sorted(IMPLEMENTATIONS)}"
            )

        python_symbols, symbol_errors = _string_list(
            row.get("python_symbols"), f"{row_id}.python_symbols", allow_empty=False
        )
        del python_symbols
        errors.extend(symbol_errors)
        rust_symbols, symbol_errors = _string_list(
            row.get("rust_symbols"), f"{row_id}.rust_symbols", allow_empty=True
        )
        errors.extend(symbol_errors)
        evidence, evidence_errors = _string_list(
            row.get("evidence"), f"{row_id}.evidence", allow_empty=True
        )
        errors.extend(evidence_errors)

        for field in ("scope", "notes"):
            value = row.get(field)
            if not isinstance(value, str) or not value.strip():
                errors.append(f"{row_id}.{field} must be a nonempty string")
        if not _safe_relative_path(row.get("source")):
            errors.append(f"{row_id}.source must be a safe nonempty upstream-relative path")

        if status == "supported" and not evidence:
            errors.append(f"{row_id}.evidence must not be empty for supported rows")
        if status not in NO_REQUIRED_RUST_SURFACE and not rust_symbols:
            errors.append(f"{row_id}.rust_symbols must name the supported Rust surface")
        if status in NO_REQUIRED_RUST_SURFACE and not rust_symbols and implementation != "none":
            errors.append(
                f"{row_id}.implementation must be 'none' when no Rust surface is named"
            )
        if status in NO_REQUIRED_RUST_SURFACE and rust_symbols and implementation == "none":
            errors.append(
                f"{row_id}.implementation must name how the listed Rust surface is implemented"
            )
        if status == "python_only" and rust_symbols:
            errors.append(f"{row_id}.rust_symbols must be empty for status 'python_only'")
        if status in {"supported", "partial"} and implementation == "none":
            errors.append(f"{row_id}.implementation cannot be 'none' for status '{status}'")
        errors.extend(_validate_evidence(root, row_id, evidence))

    duplicate_ids = sorted({row_id for row_id in ids if ids.count(row_id) > 1})
    for row_id in duplicate_ids:
        errors.append(f"{row_id}.id is duplicate")
    if ids != sorted(ids):
        first_out_of_order = next(
            current for previous, current in zip(ids, ids[1:]) if previous > current
        )
        errors.append(f"{first_out_of_order}.id is out of order; api IDs must be sorted")

    errors.extend(_validate_manifest(root, ledger))
    return errors


def render_markdown(ledger: dict[str, Any]) -> str:
    """Render the deterministic schema-stage inventory used by ``--check``."""

    rows = sorted(ledger.get("api", []), key=lambda row: row.get("id", ""))
    lines = [
        GENERATED_HEADER.rstrip("\n"),
        "",
        "This generated schema-stage inventory lists explicit compatibility claims.",
        "The full status-grouped presentation is generated in the next implementation task.",
        "",
        "## Inventory",
        "",
    ]
    lines.extend(f"- `{row['id']}` — {row['status']}" for row in rows)
    return "\n".join(lines) + "\n"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="validate the ledger and generated page")
    mode.add_argument("--write", action="store_true", help="write the generated page")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the compatibility checker command line interface."""

    arguments = _parser().parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    ledger_path = root / "compat" / "pytorch_api.toml"
    try:
        ledger = load_ledger(ledger_path)
    except (OSError, tomllib.TOMLDecodeError) as error:
        print(f"error: cannot load {ledger_path.relative_to(root)}: {error}", file=sys.stderr)
        return 1

    errors = validate_ledger(root, ledger)
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1

    coverage_path = root / "docs" / "api-coverage.md"
    expected = render_markdown(ledger)
    if arguments.write:
        print(
            "error: --write is reserved for the full public renderer in Task 2",
            file=sys.stderr,
        )
        return 2

    try:
        actual = coverage_path.read_text(encoding="utf-8")
    except OSError:
        actual = ""
    if actual != expected:
        print(
            "error: docs/api-coverage.md is stale; regenerate it with "
            "`python3 scripts/check-compatibility.py --write`",
            file=sys.stderr,
        )
        return 1
    print("compatibility ledger and generated documentation are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
